// <auto-generated />
using System;
using HyperWhisper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyperWhisper.Migrations
{
    [DbContext(typeof(HyperWhisperDbContext))]
    partial class HyperWhisperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HyperWhisper.Data.Entities.Mode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Capitalization")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudAccuracyTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudPostProcessingModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudTranscriptionDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudTranscriptionModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomInstructions")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CustomVocabulary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableScreenOCR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishSpelling")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignPlatformExtensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiCustomPrompt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemProvided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalParakeetModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPostProcessingModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostProcessingMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostProcessingProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProfanityFilter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Punctuation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemoveTrailingPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSystemPrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.RecordingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationInSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SampleRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("RecordingSessions");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("FailedReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRetryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostProcessedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostProcessingProvider")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecordingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscribedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrimmedAudioFilePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RecordingSessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.UsageTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<long>("DailyTranscriptionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstUsageDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastValidationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalModelsDownloaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UsageTracking");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.VocabularyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Word");

                    b.ToTable("VocabularyItems");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.Transcript", b =>
                {
                    b.HasOne("HyperWhisper.Data.Entities.RecordingSession", "RecordingSession")
                        .WithOne("Transcript")
                        .HasForeignKey("HyperWhisper.Data.Entities.Transcript", "RecordingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecordingSession");
                });

            modelBuilder.Entity("HyperWhisper.Data.Entities.RecordingSession", b =>
                {
                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
