using HyperWhisper.ModelManagement;
using HyperWhisper.ModelReadiness;

namespace HyperWhisper.PortableApplication;

/// <summary>A model's (speed, accuracy) pair, each 1-5, as the Model Library gauges draw it.</summary>
public readonly record struct ModelRating(int Speed, int Accuracy);

/// <summary>
/// The empirical speed/accuracy ratings behind the Model Library's "Speed / Accuracy" column,
/// sourced from the macOS benchmark in <c>benchmarks/</c> (regenerated by
/// <c>benchmarks/propose_ratings.py</c> and <c>benchmarks/propose_pp_ratings.py</c>).
///
/// This is the SHARED copy. Two hand-maintained copies of these numbers already existed, in
/// app/windows/HyperWhisper/Services/ModelLibraryManager.cs (lines ~446-559) and in
/// app/macos/hyperwhisper/Managers/ModelLibraryManager.swift, and the Linux head had no copy at
/// all, which is why its third column showed a readiness word where the other two draw meters.
/// The tables live here now so a rating is edited in one place. The Windows head still compiles
/// its own private dictionaries: this branch is not allowed to edit app/windows, so deleting
/// them and pointing ModelLibraryManager at this type is the follow-up, and until that lands
/// ModelRatingsParityTests pins the two sets equal by parsing the Windows source. Do not "fix" a
/// number here alone; change it here and let that test tell you what else to update.
///
/// FOUR tables, not one, and the split is load-bearing: six ids appear in both
/// <see cref="Cloud"/> and <see cref="PostProcessing"/> with DIFFERENT values (gemini-2.5-flash,
/// gemini-2.5-pro, gemini-3.6-flash, gemini-3-flash-preview, gemini-3.1-pro-preview,
/// gemini-3.1-flash-lite), because a model that transcribes well does not necessarily clean text
/// up well. Merging the dictionaries would silently corrupt all six.
/// </summary>
public static class ModelRatings
{
    /// <summary>The rating an unmeasured model gets: "average, unmeasured".</summary>
    public static readonly ModelRating Default = new(3, 3);

    /// <summary>
    /// Parakeet's fallback is deliberately NOT <see cref="Default"/>. Every model on this
    /// runtime is a fast transducer, so an unmeasured one is far likelier to be a 5 for speed
    /// than a 3. Mirrors ModelLibraryManager.cs:132.
    /// </summary>
    public static readonly ModelRating ParakeetDefault = new(5, 3);

    public static readonly IReadOnlyDictionary<string, ModelRating> Cloud =
        new Dictionary<string, ModelRating>(StringComparer.Ordinal)
        {
            // OpenAI
            ["gpt-4o-mini-transcribe-2025-12-15"] = new(4, 3),
            ["gpt-4o-transcribe"] = new(4, 2),
            ["gpt-4o-mini-transcribe"] = new(4, 3),
            ["whisper-1"] = new(3, 3),
            ["gpt-transcribe"] = new(4, 3),
            ["gpt-live-transcribe"] = new(5, 3),
            // Groq
            ["whisper-large-v3-turbo"] = new(5, 4),
            ["whisper-large-v3"] = new(5, 3),
            // Deepgram
            ["nova-3-general"] = new(3, 3),
            ["nova-3-medical"] = new(3, 4),
            ["nova-2-general"] = new(3, 2),
            ["nova-2-medical"] = new(3, 2),
            // AssemblyAI
            ["universal-2"] = new(3, 4),
            ["universal-3-5-pro"] = new(2, 5),
            ["universal-2-medical"] = new(2, 4),
            ["universal-3-5-pro-medical"] = new(2, 5),
            // ElevenLabs
            ["scribe_v1"] = new(3, 5),
            ["scribe_v2"] = new(3, 5),
            // Mistral
            ["voxtral-mini-latest"] = new(4, 2),
            // Soniox
            ["stt-async-v5"] = new(2, 5),
            // Gemini
            ["gemini-2.5-flash"] = new(2, 4),
            ["gemini-2.5-flash-lite"] = new(3, 3),
            ["gemini-2.5-pro"] = new(1, 5),
            ["gemini-3.1-flash-lite"] = new(3, 4),
            ["gemini-3.6-flash"] = new(2, 4),
            ["gemini-3-flash-preview"] = new(2, 1),
            ["gemini-3.1-pro-preview"] = new(1, 5),
        };

    public static readonly IReadOnlyDictionary<string, ModelRating> Whisper =
        new Dictionary<string, ModelRating>(StringComparer.Ordinal)
        {
            ["tiny"] = new(5, 1),
            ["tiny.en"] = new(5, 1),
            ["base"] = new(5, 1),
            ["base.en"] = new(5, 2),
            ["small"] = new(4, 2),
            ["small.en"] = new(5, 2),
            ["medium"] = new(4, 3),
            ["medium.en"] = new(4, 2),
            ["large-v2"] = new(3, 3),
            ["large-v3"] = new(3, 3),
            ["large-v3-turbo"] = new(4, 3),
        };

    public static readonly IReadOnlyDictionary<string, ModelRating> Parakeet =
        new Dictionary<string, ModelRating>(StringComparer.Ordinal)
        {
            ["parakeet-v2"] = new(5, 3),
            ["parakeet-v3"] = new(5, 3),
            // Qwen3 decodes autoregressively on CPU: slower than the transducer, but strong on
            // Japanese/CJK.
            ["qwen3-asr-0.6b"] = new(3, 4),
            // Nemotron-3.5 streaming transducer: fast (real-time-class on CPU), multilingual.
            // Accuracy is PROVISIONAL until measured against v3 on a real clip; per-VAD-segment
            // streaming may trail offline beam search.
            ["nemotron-3.5-ml-560ms"] = new(5, 4),
        };

    public static readonly IReadOnlyDictionary<string, ModelRating> PostProcessing =
        new Dictionary<string, ModelRating>(StringComparer.Ordinal)
        {
            ["gpt-4.1"] = new(4, 5),
            ["gpt-5.1"] = new(4, 5),
            ["gpt-4.1-mini"] = new(4, 5),
            ["gpt-5.2"] = new(4, 5),
            ["gpt-5.4"] = new(3, 5),
            ["gpt-5.4-nano"] = new(4, 4),
            ["gpt-5.4-mini"] = new(4, 4),
            ["gpt-5.6-luna"] = new(4, 4),
            ["gpt-5-mini"] = new(1, 4),
            ["gpt-5"] = new(1, 4),
            ["gpt-5-nano"] = new(1, 4),
            ["claude-sonnet-4-6"] = new(4, 5),
            ["claude-sonnet-5"] = new(4, 5),
            ["claude-sonnet-4-5"] = new(3, 5),
            ["claude-haiku-4-5"] = new(4, 4),
            ["gemini-2.5-flash"] = new(2, 5),
            ["gemini-3.5-flash"] = new(2, 5),
            ["gemini-3.6-flash"] = new(2, 5),
            ["gemini-3.7-flash"] = new(2, 5),
            ["gemini-2.5-flash-lite"] = new(4, 5),
            ["gemini-3.5-flash-lite"] = new(5, 4),
            ["gemini-2.5-pro"] = new(2, 4),
            ["gemini-3-flash-preview"] = new(1, 4),
            ["gemini-3.1-pro-preview"] = new(2, 3),
            ["gemini-3.1-flash-lite"] = new(4, 3),
            ["openai/gpt-oss-120b"] = new(4, 4),
            ["openai/gpt-oss-20b"] = new(4, 4),
            ["qwen/qwen3.6-27b"] = new(4, 3),
            ["grok-4.3"] = new(2, 5),
            ["grok-4.5"] = new(2, 5),
            ["grok-4.6"] = new(2, 5),
            ["mistral-small-latest"] = new(2, 3),
            ["mistral-medium-3.5"] = new(2, 4),
            ["gpt-oss-120b"] = new(5, 3),
            ["gemma-4-31b"] = new(4, 3),
            ["gemma-4-E2B-it-Q4_K_M.gguf"] = new(5, 1),
            ["gemma-4-E4B-it-Q4_K_M.gguf"] = new(4, 2),
            ["gemma-4-12b-it-Q4_K_M.gguf"] = new(3, 3),
            ["gemma-4-26B-A4B-it-UD-Q4_K_M.gguf"] = new(2, 4),
            ["gemma-4-31B-it-Q4_K_M.gguf"] = new(1, 5),
        };

    /// <summary>
    /// The rating for one catalog row, picking the table the Windows row builder would have
    /// picked. Windows chooses by which builder emitted the row, not by provider, so the
    /// selection below reproduces that split from the capability instead:
    ///
    ///   BuildCloudTranscriptionRows  -> <see cref="Cloud"/>, keyed on the model id
    ///   BuildWhisperRows             -> <see cref="Whisper"/> (Windows keys on model.Type,
    ///                                   which is the same string as the portable catalog's
    ///                                   ManagedModel.Id: "base", "large-v3-turbo", ...)
    ///   BuildParakeetRows            -> <see cref="Parakeet"/>, fallback (5,3)
    ///   BuildPostProcessingRows      -> <see cref="PostProcessing"/>
    ///   BuildLocalLlmRows            -> a FLAT (3, recommended ? 4 : 3); see below
    ///   BuildCustomEndpointRows      -> a flat (3,3)
    ///
    /// The local-LLM case is the subtle one. Every gemma GGUF also has an entry in
    /// <see cref="PostProcessing"/>, but Windows does NOT use it for these rows: it hard-codes
    /// (3, recommended ? 4 : 3) at ModelLibraryManager.cs:220-221, because the GGUF's real
    /// throughput depends on the machine's GPU offload rather than on the model. Reading the
    /// PostProcessing entry here instead would show Gemma 4 E2B as 5/1 where Windows shows 3/4.
    /// </summary>
    public static ModelRating For(ModelCapability capability, ManagedModel? model = null)
    {
        ArgumentNullException.ThrowIfNull(capability);

        if (capability.Surface == ModelSurface.CustomEndpoint) return Default;

        // On-device text models are the local-LLM rows, whatever surface the catalog files
        // them under. Checked before the PostProcessing branch on purpose.
        if (capability.Deployment == ModelDeployment.Local && capability.Workload == ModelWorkload.Text)
            return new ModelRating(3, model?.IsRecommended == true ? 4 : 3);

        if (capability.Surface == ModelSurface.PostProcessing)
            return Lookup(PostProcessing, capability.ModelId, Default);

        if (capability.Deployment == ModelDeployment.Local)
        {
            // "parakeet", "parakeetLocal" and "nemotronLocal" are all the sherpa-onnx runtime;
            // the streaming rows are a second capability over the same ManagedModel.
            return capability.ProviderId.StartsWith("parakeet", StringComparison.OrdinalIgnoreCase)
                || capability.ProviderId.StartsWith("nemotron", StringComparison.OrdinalIgnoreCase)
                ? Lookup(Parakeet, capability.ModelId, ParakeetDefault)
                : Lookup(Whisper, capability.ModelId, Default);
        }

        return Lookup(Cloud, capability.ModelId, Default);
    }

    private static ModelRating Lookup(IReadOnlyDictionary<string, ModelRating> table, string id, ModelRating fallback)
        => table.TryGetValue(id, out var rating) ? rating : fallback;
}
