//
//  RustHTTPExecutorBase64Tests.swift
//  hyperwhisperTests
//
//  Pins the chunked base64 encoder behind the inline-base64 JSON body
//  (`Body.jsonWithBase64File`, the Gemini 3.5 Transcribe `/v1beta/interactions`
//  upload) and the inline-request builder's refusal to drop a file-backed body.
//
//  WHY THE SIZES MATTER: the encoder reads 1.5 MB at a time and may only emit
//  whole 3-byte groups, carrying the 1- or 2-byte remainder into the next read —
//  padding is legal only at the very end of a base64 stream. Every size below
//  1.5 MB takes a single pass and exercises none of that. A carry regression
//  would therefore corrupt ONLY recordings larger than 1.5 MB while every other
//  test stayed green, and the corruption reaches the user as Google rejecting
//  the audio, with nothing local to point at.
//
//  Fixtures are generated byte patterns written to the temp directory: no real
//  recordings, no keys, no network.
//

import Foundation
import Testing
@testable import HyperWhisper

@Suite("Inline-base64 request body")
struct RustHTTPExecutorBase64Tests {

    /// A deterministic, NON-repeating-mod-3 pattern. A pattern with period 3
    /// would encode identically no matter where the chunk boundary fell, which
    /// is exactly the bug this suite exists to catch, so the period is 251 — a
    /// prime, coprime with both 3 and the chunk size.
    private static func pattern(_ count: Int) -> Data {
        var bytes = [UInt8]()
        bytes.reserveCapacity(count)
        for i in 0..<count {
            bytes.append(UInt8((i % 251)))
        }
        return Data(bytes)
    }

    /// Writes `data` to a throwaway directory and hands the body `(source,
    /// output)` URLs. Deliberately non-generic and `Void`-returning so the
    /// call sites need no closure type annotation.
    private static func withTempFile(
        containing data: Data,
        _ body: (URL, URL) throws -> Void
    ) throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("hw-b64-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let source = directory.appendingPathComponent("audio.bin")
        try data.write(to: source)
        let output = directory.appendingPathComponent("body.json")
        try body(source, output)
    }

    /// Encode `size` bytes through the production writer and compare against a
    /// whole-file `base64EncodedData()`.
    ///
    /// The comparison is bound to a `Bool` before `#expect` deliberately: a bare
    /// `#expect(a == b)` on multi-megabyte `Data` would dump both operands into
    /// the failure message.
    private func assertEncodes(size: Int) throws {
        let audio = Self.pattern(size)
        let prefix = Data(#"{"audio":{"data":""#.utf8)
        let suffix = Data(#""}}"#.utf8)

        try Self.withTempFile(containing: audio) { source, output in
            try RustHTTPExecutor.writeJSONWithBase64Body(
                to: output,
                prefix: prefix,
                path: source.path,
                suffix: suffix
            )
            let written = try Data(contentsOf: output)
            let expected = prefix + audio.base64EncodedData() + suffix

            let matches = written == expected
            #expect(
                matches,
                """
                base64 body differs from a whole-file encode at \(size) bytes \
                (chunk size \(RustHTTPExecutor.base64ChunkSize)). Wrote \(written.count) bytes, \
                expected \(expected.count).
                """
            )
        }
    }

    // MARK: - Small sizes, including every remainder mod 3

    @Test("Sizes below one chunk encode identically to a whole-file encode",
          arguments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 100, 1024, 1025, 1026])
    func smallSizesMatch(size: Int) throws {
        // 1 and 2 are the padded tails; 0 is the empty body (no `==` at all).
        try assertEncodes(size: size)
    }

    // MARK: - Around and above the 1.5 MB chunk boundary

    @Test("Sizes straddling the chunk boundary encode identically",
          arguments: [-2, -1, 0, 1, 2, 3])
    func chunkBoundaryOffsetsMatch(offset: Int) throws {
        // The boundary itself is 3-byte aligned, so `chunkSize` and
        // `chunkSize - 1` / `+1` / `+2` cover a zero, two-byte and one-byte
        // carry into the second read.
        try assertEncodes(size: RustHTTPExecutor.base64ChunkSize + offset)
    }

    @Test("Multi-chunk sizes not divisible by 3 encode identically",
          arguments: [
            // Two full reads plus a 1-byte tail, and plus a 2-byte tail.
            2 * (3 * 512 * 1024) + 1,
            2 * (3 * 512 * 1024) + 2,
            // A size that is not chunk-aligned AND not divisible by 3, so the
            // carry differs on every read.
            3_000_001,
            // Comfortably past the boundary, one byte short of a group.
            2_000_000,
          ])
    func multiChunkSizesMatch(size: Int) throws {
        try assertEncodes(size: size)
    }

    @Test("The chunk read size stays 3-byte aligned")
    func chunkSizeIsThreeByteAligned() {
        // The carry logic is correct either way, but a misaligned chunk makes
        // EVERY read carry, which is the slow path and a silent perf regression.
        #expect(RustHTTPExecutor.base64ChunkSize % 3 == 0)
        #expect(RustHTTPExecutor.base64ChunkSize > 0)
    }

    @Test("The encoding is the standard padded alphabet with no line breaks")
    func encodingUsesTheContractedAlphabet() throws {
        // Google rejects the audio for a URL-safe alphabet, wrapped lines or
        // missing padding. 4 bytes forces one pad character.
        let audio = Data([0xFB, 0xFF, 0xBF, 0x00])
        try Self.withTempFile(containing: audio) { source, output in
            try RustHTTPExecutor.writeJSONWithBase64Body(
                to: output, prefix: Data(), path: source.path, suffix: Data()
            )
            let bodyData = try Data(contentsOf: output)
            let written = try #require(String(data: bodyData, encoding: .utf8))
            #expect(written == audio.base64EncodedString())
            #expect(written.hasSuffix("=="), "the tail must be padded")
            #expect(!written.contains("\n") && !written.contains("\r"))
            // URL-safe would spell these as `-` and `_`.
            #expect(written.contains("+") || written.contains("/"))
        }
    }

    // MARK: - buildInlineURLRequest must not drop a body it cannot attach

    private static func request(body: Body) -> HttpRequest {
        HttpRequest(
            method: .post,
            url: "https://example.invalid/v1/thing",
            headers: [Header(name: "Authorization", value: "Bearer fixture")],
            body: body
        )
    }

    @Test("Inline bodies are attached")
    func inlineBodiesAreAttached() throws {
        let payload = Data(#"{"hello":"world"}"#.utf8)
        let attached = try RustHTTPExecutor.buildInlineURLRequest(
            from: Self.request(body: .bytes(contentType: "application/json", data: payload))
        )
        #expect(attached.httpBody == payload)
        #expect(attached.value(forHTTPHeaderField: "Authorization") == "Bearer fixture")

        let empty = try RustHTTPExecutor.buildInlineURLRequest(from: Self.request(body: .empty))
        #expect(empty.httpBody == nil)
    }

    @Test("A file-backed body is refused, not silently dropped")
    func fileBackedBodiesAreRefused() {
        // Returning the request without its body would put a fully-formed,
        // correctly-authenticated call with an EMPTY payload on the wire, which
        // reads at the call site as the provider rejecting valid input.
        let fileBacked: [Body] = [
            .fileStream(path: "/tmp/does-not-matter.wav", contentType: "audio/wav"),
            .multipart(boundary: "b", parts: [
                .fileRef(field: "file", path: "/tmp/x.wav", mime: "audio/wav", filename: "x.wav"),
            ]),
            .jsonWithBase64File(prefix: Data("{".utf8), path: "/tmp/x.wav", suffix: Data("}".utf8)),
        ]
        for body in fileBacked {
            #expect(throws: (any Error).self) {
                _ = try RustHTTPExecutor.buildInlineURLRequest(from: Self.request(body: body))
            }
        }
    }

    @Test("A missing source file throws instead of writing a truncated body")
    func aMissingSourceFileThrows() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("hw-b64-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let output = directory.appendingPathComponent("body.json")
        #expect(throws: (any Error).self) {
            try RustHTTPExecutor.writeJSONWithBase64Body(
                to: output,
                prefix: Data("{".utf8),
                path: directory.appendingPathComponent("does-not-exist.bin").path,
                suffix: Data("}".utf8)
            )
        }
    }

    @Test("A typed multipart file survives the Swift binding beside streamed audio")
    func typedMultipartFileAndStreamedAudioAreWritten() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("hw-multipart-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let audio = directory.appendingPathComponent("input.wav")
        let output = directory.appendingPathComponent("body.multipart")
        try Data("streamed-audio-marker".utf8).write(to: audio)
        let metadata = Data(#"{"mode":"PUSH_TO_TALK"}"#.utf8)

        try RustHTTPExecutor.writeMultipartBody(
            to: output,
            boundary: "test-boundary",
            parts: [
                .inlineFile(
                    field: "request",
                    filename: "request.json",
                    mime: "application/json",
                    data: metadata
                ),
                .fileRef(
                    field: "audio",
                    path: audio.path,
                    mime: "audio/wav",
                    filename: "audio.wav"
                ),
            ]
        )

        let rendered = String(decoding: try Data(contentsOf: output), as: UTF8.self)
        #expect(rendered.contains(#"name="request"; filename="request.json""#))
        #expect(rendered.contains("Content-Type: application/json"))
        #expect(rendered.contains(#"{"mode":"PUSH_TO_TALK"}"#))
        #expect(rendered.contains(#"name="audio"; filename="audio.wav""#))
        #expect(rendered.contains("streamed-audio-marker"))
    }
}
